### PR TITLE
Update golang to 1.22.4

### PR DESCRIPTION
**Pull request by louisjimenez**

### CODE REVIEW

**Comment by droot** [comment]
I think there is an test failure that is unrelated to this PR. The fix for that test probably requires filtering out the `DEPRECATION NOTICE` message from the docker.

```
FAIL: TestContainerFn (0.64s)
    --- FAIL: TestContainerFn/simple_busybox (0.38s)
        container_test.go:67: 
            	Error Trace:	/home/runner/work/kpt/kpt/go/src/github.com/GoogleContainerTools/kpt/internal/fnruntime/container_test.go:67
            	Error:      	Received unexpected error:
            	            	  Stderr:
            	            	    "docker: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of gcr.io/google-containers/busybox:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at [https://docs.docker.com/go/deprecated-image-specs/.](https://docs.docker.com/go/deprecated-image-specs/)"
            	            	    "See 'docker run --help'."
            	            	  Exit Code: 125
            	Test:       	TestContainerFn/simple_busybox
FAIL
```

**Comment by droot** [comment]
@louisjimenez can we bump the Go version to 1.22.4 ?

**Comment by louisjimenez** [comment]
> @louisjimenez can we bump the Go version to 1.22.4 ?

Done

**Comment by louisjimenez** [comment]
Can we pull in the fix here https://github.com/kptdev/kpt/pull/4165?

**Comment by droot** [comment]
> Can we pull in the fix here #4165?

Let's copy that change here and get it in with this. Makes sense.

**Comment by louisjimenez** [comment]
> > Can we pull in the fix here #4165?
> 
> Let's copy that change here and get it in with this. Makes sense.

Cherry-picked the fix.

**Pull request merged**
